version: '3'
services:
  demo-deepfake-api:
    image: deepfake-api:v1.0.0
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    runtime: nvidia
    volumes:
      - ./:/app
    command: uvicorn app:app --host 0.0.0.0 --port ${API_PORT}
