version: '3'
services:
  demo-deepfake-api:
    container_name: demo-deepfake-detection
    image: deepfake-api:v1.0.0
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    #runtime: gpus
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./:/app
    command: uvicorn app:app --host 0.0.0.0 --port ${API_PORT} --reload
