defaults:
  - _self_
  - logger: [default]
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

# Override hydra output directory
hydra:
  run:
    dir: .
  output_subdir: null